# Generated by Django 4.2.7 on 2023-11-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_syllabus_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='Интернет ресурсы'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Обязательная литература'),
        ),
    ]
