# Generated by Django 4.2.7 on 2023-11-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_alter_literature_author_alter_literature_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Интернет ресурсы'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Обязательная литература'),
        ),
    ]
