# Generated by Django 4.2.7 on 2023-11-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_alter_thematicplan_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thematicplan',
            name='syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.syllabus', verbose_name='Силлабус'),
        ),
    ]
