# Generated by Django 4.2.7 on 2023-11-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0008_alter_thematicplan_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.syllabus'),
        ),
    ]
