# Generated by Django 4.2.7 on 2023-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_alter_learningoutcome_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningoutcome',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='syllabuses',
            field=models.ManyToManyField(to='syllabus.syllabus'),
        ),
    ]
