# Generated by Django 4.2.7 on 2023-11-11 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0010_remove_learningoutcome_syllabus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningoutcome',
            name='syllabuses',
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.syllabus'),
        ),
    ]
