# Generated by Django 4.2.7 on 2023-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0011_remove_learningoutcome_syllabuses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание результата обучения курса')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание результата обучения образовательной программы')),
            ],
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='learning_outcome_course',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='learning_outcome_program',
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='learning_outcome_course',
            field=models.ManyToManyField(to='syllabus.courseoutcome', verbose_name='Результаты обучения курса (РО курса)'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='learning_outcome_program',
            field=models.ManyToManyField(to='syllabus.programoutcome', verbose_name='Результаты обучения образовательной программы (РО ОП)'),
        ),
    ]
